### PR TITLE
[WIP] Webpack 4 upgrade

### PR DESCRIPTION
**Pull request by grgur**
This is a big Webpack upgrade PR. Webpack config has been rewritten to support Webpack 4. 

### Before
```sh
static/mclogo-22f11896.svg    2.57 kB          [emitted]
             0-8a3409a0.js    5.44 kB       0  [emitted]
       reports-7d2f42ac.js     202 kB       1  [emitted]  reports
        budget-094f9553.js    22.4 kB       2  [emitted]  budget
          main-9969177b.js     186 kB       3  [emitted]  main
        style-489ad2ac.css    4.08 kB       3  [emitted]  main
    style-489ad2ac.css.map  300 bytes       3  [emitted]  main
                index.html  642 bytes          [emitted]
```

### After
```sh
                  Asset       Size  Chunks             Chunk Names
static/mclogo-22f11.svg   2.51 KiB          [emitted]
                  0.css    3.1 KiB       0  [emitted]  budget
         budget-133c.js   21.6 KiB       0  [emitted]  budget
                  1.css    1.3 KiB       1  [emitted]  reports
        reports-cc65.js    142 KiB       1  [emitted]  reports
   static/main.6285.css   2.89 KiB       2  [emitted]  main
           main-6285.js    165 KiB       2  [emitted]  main
             index.html  644 bytes          [emitted]
```

## Checklist

* [x] Webpack upgrade
* [x] Dependency upgrade (most of them)
* [x] Automatic polyfills (`babel-env`) - this should fix IE issues
* [x] Vulnerable npm packages upgraded (deep)
* [x] Created/updated unit tests
* [x] Removed `yarn.lock` since yarn now supports `package-lock.json`
* [x] Load D3 asynchronously (`react-loadable`?)
* [x] Use D3 v5
* [x] Fix flow
> flow sometimes shows no issues and sometimes shows a bunch of them

### CODE REVIEW

**Comment by ErnestoR** [comment]
@grgur  I've updated D3 to v5 in a separate PR https://github.com/ModusCreateOrg/budgeting/pull/182

**Comment by grgur** [comment]
You're the man @ErnestoR! Thank you so much.

**Comment by rathorebs** [comment]
D:\wamp64\www\workmob\jodha01>npm run start

> webpack-react-redux-budget-app-sample@2.0.0 start D:\wamp64\www\workmob\jodha01
> webpack-dev-server --config webpack.config.dev.js

i ?wds?: Project is running at http://localhost:8000/
i ?wds?: webpack output is served from /
i ?wds?: Content not from webpack is served from D:\wamp64\www\workmob\jodha01\app
i ?wds?: 404s will fallback to /index.html
x ?wdm?: Time: 2650ms
Built at: 2018-06-27 19:37:01
            Asset       Size          Chunks             Chunk Names
static/mclogo.svg   2.51 KiB                  [emitted]
        budget.js   95.2 KiB          budget  [emitted]  budget
budget~reports.js   18.6 KiB  budget~reports  [emitted]  budget~reports
         front.js    463 KiB           front  [emitted]  front
       reports.js   83.3 KiB         reports  [emitted]  reports
      libs.dll.js   2.24 MiB                  [emitted]
       index.html  232 bytes                  [emitted]
Entrypoint front = front.js (prefetch: budget~reports.js reports.js budget.js)

ERROR in   Error: HtmlWebpackPlugin: could not load file D:\wamp64\www\workmob\jodha01\dll\libs.dll.js.map

  - index.js:337 Promise.all.then.catch
    [jodha01]/[html-webpack-plugin]/index.js:337:33



i ?wdm?: Failed to compile.

**Comment by grgur** [comment]
@rathorebs Thanks for catching that. Fixed in the most recent commit

**Comment by ecris87** [comment]
Hi @grgur,

Regarding the last remaining task here _Load D3 asynchronously (react-loadable?)_
I've used react-loadable for component centric splitting. I applied the hoc provided by that lib to the 2 charts used in the app: 0b2ea8aad61a083c136d26093b5b5d9b1da1f777.
Let me know if this looks ok to you and if it's what you envisioned for this task. 

Some stats:

### Lighthouse on localhost:3000/#/budget
**Before:**
image

**After:**
image

### Lighthouse on localhost:3000/#/reports/inflow-outflow
**Before:**
image

**After:**
image

These values are estimated and may vary but i've consistently seen better results with the app after the react-loadable changes.

### Bundles
Bundles differences can be seen by comparing these 2 builds:
- https://circleci.com/gh/ModusCreateOrg/budgeting/494
- https://circleci.com/gh/ModusCreateOrg/budgeting/495

**Pull request merged**
