### PR TITLE
Add tests for EntryFormRow

### PR DESCRIPTION
**Pull request by jlangevin**
## Proposed Changes

* Adds tests for new and previously-existing buttons 
* Update enzyme-adapter-react-16 to fix error throw by mount()

## Screenshot

image

image

## Checklist

* [ ] Feature developed
* [x] Created/updated unit tests
* [x] Comments in code
* [ ] Documentation written

### CODE REVIEW

**Comment by grgur** [comment]
You crushed it! Thanks @jlangevin

**Comment by grgur** [comment]
@jlangevin just wondering - how did you find this and how are you using the app? I'm just curious to learn about use cases.

**Comment by jlangevin** [comment]
@grgur To be honest, I'm not using at the moment.  However, I've been kicking around an idea for a budget-related app and might use it as a starter.  If I do, I'd want editing and deleting and figured others would as well.  So I used this as an opportunity to get familiar with the code, and this way others can benefit too.  As for how I found this, I'm friends with Tim Eagan and clicked through to Modus Create's repos on a whim the other day.  Thanks for putting this stuff out there.  I always enjoy learning how other folks approach things.  I also hadn't used Code Climate before, which dare I say, I've really grown to like.

**Comment by jlangevin** [comment]
@grgur Also, thanks for the kind words on my work!

**Pull request merged**
