### PR TITLE
Fix #188 add husky & lint-staged for pre-commit linting

### LINKED ISSUE #188: Automatically format files using Prettier in a pre-commit hook
Automatically format files using Prettier in a pre-commit hook. Guide: https://prettier.io/docs/en/precommit.html

Going with option 1, this would require adding 2 new dev dependencies: lint-staged and husky.

### PR DESCRIPTION
**Pull request by nelsonomuto**
## Proposed Changes
Fix #188 
Add husky & lint-staged, update package.json scripts to run precommit hook to lint and fix staged files
## Screenshot
screen shot 2018-09-03 at 12 28 49 pm

## Checklist

* [x] Feature developed
* [x] Created/updated unit tests (N/A)
* [x] Comments in code (N/A)
* [x] Documentation written (N/A)

### CODE REVIEW

**Comment by grgur** [comment]
Once yarn.lock is removed, you'll have to run `npm i` to update package-lock.json

**Comment by nelsonomuto** [comment]
@grgur yarn.lock is out

**Comment by grgur** [comment]
There seems to be an issue with a package here. That's why the build is failing.
@ecris87 recently upgraded Babel to v7 and resolved this issue in #200 

Can you merge with master (upstream) and run `npm i`? I just tried that and it worked fine. I don't have access to your branch so I can't push it :)

**Comment by grgur** [comment]
Fantastic! Thanks @nelsonomuto

**Pull request merged**
